apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  labels:
    component: db
spec:
  selector:
    matchLabels:
      component: db
  serviceName: database
  replicas: 1
  template:
    metadata:
      labels:
        component: db
    spec:
      containers:
        - name: example-api-database
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: timezone
            - name: PGTZ
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: timezone
          image: postgres:13
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb-data
              subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
